# Generated by Django 5.1 on 2024-08-22 00:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(max_length=100)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('fecha_entrada', models.DateField(default=django.utils.timezone.now)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_entrada'],
                'indexes': [models.Index(fields=['nombre_producto'], name='stock_inven_nombre__8a355b_idx'), models.Index(fields=['fecha_entrada'], name='stock_inven_fecha_e_f00f24_idx')],
            },
        ),
    ]
